<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.5;
        }
        .header {
            border-bottom: 2px solid #198754;
            padding-bottom: 15px;
            margin-bottom: 25px;
        }
        .header h1 {
            color: #198754;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0 0;
            font-size: 11px;
            color: #666;
            text-transform: uppercase;
        }
        .meta {
            margin-bottom: 20px;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 11px;
        }
        th {
            background-color: #f2f2f2;
            color: #000;
            font-weight: bold;
            border: 1px solid #ccc;
            padding: 10px;
            text-align: left;
            text-transform: uppercase;
        }
        td {
            border: 1px solid #eee;
            padding: 8px 10px;
            text-align: left;
        }
        tr:nth-child(even) {
            background-color: #fafafa;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            font-size: 9px;
            color: #999;
            text-align: center;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Permaculture Management System</h1>
        <p>{{ $title }}</p>
    </div>

    <div class="meta">
        <strong>Report Date:</strong> {{ date('d M, Y | h:i A') }}<br>
        <strong>Generated By:</strong> Administrator
    </div>

    <table>
        <thead>
            <tr>
                @foreach($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
                <tr>
                    @foreach($row as $cell)
                        <td>{{ $cell }}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        © {{ date('Y') }} Permaculture ERP. This is a computer-generated document.
    </div>
</body>
</html>
